### PR TITLE
Updating the certificates for the pod-annotate example 

### PR DESCRIPTION
**Pull request by soorena776**
- Replacing the expired certificate with a new one (10 years expiry date)
- Adding a Dockerfile, and updating the Readme
- Updating the outdated Deployment version and fields

### CODE REVIEW

**Comment by slok** [comment]
Hi @soorena776, Thanks for updating the examples!

One question, Why did you created a new Dockerfile instead of using https://github.com/slok/kubewebhook/blob/master/examples/Dockerfile ?

**Comment by soorena776** [comment]
Hey @slok!
I didn't notice that Dockerfile until now. Maybe the `Reademe.md` should be updated to clearly point to it. I'll update the PR.

**Comment by soorena776** [comment]
@slok ptal!

**Comment by slok** [comment]
Hey @soorena776 Thanks for the heads-up! and sorry about that... I mossed and forget the PR :/

**Pull request merged**
