### PR TITLE
Fix admissionreview v1beta1 with null request kind and request resource

### PR DESCRIPTION
**Pull request by annymsMthd**
Signed-off-by: Joshua Benjamin <joshua.benjamin@iherb.com>

### CODE REVIEW

**Comment by annymsMthd** [comment]
Ran into this for a v1.14 cluster we have. Looks like the spec for the admissionreview has those objects as optional even for the v1 https://pkg.go.dev/k8s.io/api@v0.23.0/admission/v1beta1

Let me know if you want the tests expanded. I just did the one for coverage.

**Comment by slok** [comment]
Hi @annymsMthd thanks for the PR! I'll try to take a look this weekend.

It's strange to don't have that data (Maybe is related to the Kubernetes version) If you can share the information, could you please write the resources and operations that the webhook was trying to handle when the error occurred (for the sake of understanding more in-depth the problem).

Thanks again!

**Comment by annymsMthd** [comment]
Sure. This was a secret webhook submission to the banzai bank-vaults webhook that is using this library. This kubernetes cluster is an openstack built, I think, one from a Russian provider. It is currently running version 1.14.6 of k8s as far as I can tell. Would you like me to try to get the raw, redacted, submission object?

**Comment by slok** [comment]
Thanks for the info @annymsMthd. I think that it's enough :)

I guess that after the `v2` upgrade/refactor, this problem was created and has not been surfaced until now because is not common to use the `v2` Kubewebhook version with those Kubernetes versions. Also, I guess that on those versions when the read object didn't have a conversion of compatible type (e.g v1beta1 -> v1), it is empty.

**Review by slok — APPROVED** [review]

**Comment by annymsMthd** [comment]
Awesome. Thank you for the project!

**Pull request merged**
