### PR TITLE
Add 'Allowed' label dimension to Prometheus counter for reviews

### PR DESCRIPTION
**Pull request by towolf**
Salve,

I think it would be very useful to know how many reviews were denied and how many were allowed.

So this commit adds another label dimension to track this:

```
# HELP kubewebhook_admission_webhook_admission_reviews_total Total number of admission reviews handled.
# TYPE kubewebhook_admission_webhook_admission_reviews_total counter
kubewebhook_admission_webhook_admission_reviews_total{allowed="false",kind="validating",namespace="default",operation="CREATE",resource="/v1/pods",webhook="validate/pod"} 2                                        
kubewebhook_admission_webhook_admission_reviews_total{allowed="true",kind="validating",namespace="default",operation="CREATE",resource="/v1/pods",webhook="validate/pod"} 8             
```

### CODE REVIEW

**Comment by slok** [comment]
Hi @towolf!

Thanks for the contribution, I see that this PR adds value to the observability although mutating webhooks will _always_ have the allowed to `true`, nevermind, I think that is better than having a separate metric (also maybe some people use the mutating webhooks to validate at the same time).

Could you fix the tests please? (the signature of the metrics service interface changed so you will need to recreate the mocks with `make mocks`).

Thanks!

**Comment by towolf** [comment]
Added a commit with updated mocks, thanks for the tip. The test still fails, though. Any idea why?

Also, could you check out my comment in the other PR here? I'm still having the problem that the PR purports to fix.

https://github.com/slok/kubewebhook/pull/25#issuecomment-477363434

**Comment by towolf** [comment]
Hey @slok, did you know that the apiserver itself is also collecting latency histograms for each admission webhook?

`apiserver_admission_webhook_admission_latencies_seconds_bucket`
`apiserver_admission_webhook_admission_latencies_seconds_count`
`apiserver_admission_webhook_admission_latencies_seconds_sum`

**Comment by slok** [comment]
hi @towolf Sorry for the delay, I missed :/

The tests continue failing because they need to be changed to support the new changes. You can check the tests that are failing on the Travis logs or execute locally using `make test`.

- Check Prometheus implementation of metrics service tests to call with the correct arguments to the metric services [tests](https://github.com/slok/kubewebhook/blob/e215acc0435a09a6ace8dd3308727639160eaaa4/pkg/observability/metrics/prometheus_test.go#L1).
- Check webhook metrics decorator [tests](https://github.com/slok/kubewebhook/blob/e215acc0435a09a6ace8dd3308727639160eaaa4/pkg/webhook/internal/instrumenting/instrumenting_test.go) 

Thanks!

**Comment by slok** [comment]
Closed by #65

**Pull request closed without merging**
